name: Awesome Research Group
url: https://ralphieraccoon.github.io/research-group-web/

# Sections on the "people" page.
people_roles:
    - key: faculty
      name: Faculty
    - key: postdoc
      name: PDRA
    - key: phd
      name: PhD Students
    - key: alum
      name: Alumni

project_roles:
    - key: super
      name: Principal Investigator
    - key: cosuper
      name: Co-Investigator
    - key: phd
      name: PhD Researcher
    - key: pdra
      name: PDRA Researcher

# Base pathname for links.
base:

# make pages for the _projects folder
collections:
    projects:
        output: true
        permalink: /:collection/:name

# Navigation bar links.
navigation:
    - title: Home
      link: "/"
    - title: People
      link: /people
    - title: Research
      link: /research
    - title: Publications
      link: /publications
