name: Awesome Research Group
url: http://awesome.example.edu

# Sections on the "people" page.
people_roles:
    - key: faculty
      name: Faculty
    - key: postdoc
      name: PDRA
    - key: phd
      name: PhD Students
    - key: alum
      name: Alumni

project_roles:
    - key: super
      name: Principal Investigator
    - key: cosuper
      name: Co-Investigator
    - key: phd
      name: PhD Researcher

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
    projects:
        output: true

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people.html
    - title: Research
      link: /research.html
    - title: Publications
      link: /publications.html
